# Generated by Django 3.2.4 on 2021-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
