# Generated by Django 3.2.4 on 2021-08-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varation',
            new_name='variation',
        ),
    ]
